#!/usr/bin/env python
"""generate gtk rc file and paint widgets.
"""
import os
import re
import sys
import bitmap

class Generator():
    """
    A class for gtk2 theme generator.

    """
        
    def __init__(self, resource_dir, output_dir):
        """Setup in/out resource path and default color.

        :resource_dir: input index colored image files dir.
        :output_dir: theme saved dir.
        """
        self.__resource_dir = resource_dir
        self.__output_dir = output_dir
        self.__filter = []
        self.fg='#404040'
        self.bg='#ffffff'
        self.hfg='#ffffff'
        self.hbg='#808080'
        
    def add_filter(self, regex_format, hexcolor1, hexcolor2):
        """add regex filter."""
        self.__filter.append({u'str':regex_format, 
            u'regex':re.compile(regex_format), 
            u'color1':hexcolor1, 
            u'color2':hexcolor2})

    def clear_filter(self):
        """clear regex filter."""
        self.__filter = []

    def background(self, active, inactive):
        self.bg = inactive
        self.hbg = active

    def font(self, active, inactive):
        self.fg = inactive
        self.hfg = active

    def eventable(self, active, inactive):
        """Sets eventable object color."""
        self.add_filter(u'.+base.+', active, inactive)
        self.add_filter(u'.+normal.+', active, inactive)
        self.add_filter(u'.+active.+', active, inactive)
        self.add_filter(u'.+inactive.+', active, inactive)
        self.add_filter(u'.+hover.+', active, inactive)
        self.add_filter(u'.+pressed.+', active, inactive)

    def __paint_images(self, input_dir, output_dir, root=''):
        """Convert gray scaled images to RGB images recursively."""
        if not root:
            root= input_dir
        self.__make_dirs(output_dir)
        for i in os.listdir(input_dir):
            if os.path.isdir(input_dir+u'/'+i):
                self.__paint_images(input_dir+u'/'+i, output_dir, root)
            else:
                if i.endswith('png'):
                    image_path = input_dir+u'/'+i
                    save_path = input_dir.replace(
                        root, 
                        output_dir)+u'/'+i
                    save_dir = os.path.dirname(save_path)
                    if not os.path.exists(save_dir):
                        os.makedirs(save_dir)
                    self.__paint_image(image_path, save_path)

    def __paint_image(self, image_path, save_path):
        """paint an image and save to save_path"""
        for i in self.__filter:
            if i[u'regex'].match(image_path):
                print image_path,  i[u'color1'], i[u'color2']
                bitmap.pigment(image_path, save_path, i[u'color1'], i[u'color2'])
                break

    def __make_dirs(self, output_path):
        """Generate directory to make file."""
        if not os.path.exists(os.path.dirname(output_path)):
            print 'make: '+os.path.dirname(output_path)
            os.makedirs(os.path.dirname(output_path))

    def generate(self):
        """Write gtk2 theme files to output dir."""

        self.add_filter(u'.*', self.hbg, self.bg)
        self._copy('gtkrc')
        self.__generate_rc(self.__output_dir)
        self.__paint_images(self.__resource_dir+'/gtk-2.0/index', self.__output_dir+'/gtk-2.0/colored')

    def __generate_rc(self, output_dir):
        """generate colorrc file."""
        strings = """#author: mei raka 
            #DO NOT EDIT THIS FILE!
            style "color"    #GtkWidget
            {
            fg[NORMAL] = "%(fg_)s" 
            fg[ACTIVE] = "%(fg_)s" 
            fg[PRELIGHT] = "%(hfg_)s" 
            fg[SELECTED] = "%(fg_)s" 
            fg[INSENSITIVE] = "%(fg_)s" 
            bg[NORMAL] = "%(bg_)s" 
            bg[ACTIVE] = "%(bg_)s" 
            bg[PRELIGHT] = "%(hbg_)s"
            bg[SELECTED] = "%(hbg_)s"
            bg[INSENSITIVE] = "%(bg_)s"
            base[NORMAL] = "%(bg_)s"
            base[ACTIVE] = "%(hbg_)s" 
            base[PRELIGHT] = "%(bg_)s"
            base[INSENSITIVE] = "%(bg_)s"
            base[SELECTED]     = "%(hbg_)s"
            text[NORMAL] = "%(fg_)s"
            text[INSENSITIVE] = "%(fg_)s"
            text[SELECTED] = "%(fg_)s"
            text[ACTIVE] = "%(fg_)s"
            text[PRELIGHT]     = "%(bg_)s"
            }
            class "GtkWidget" style "color"
            class "GtkWindow" style "color"

            style "toolbar-color"
            {
            bg[NORMAL] = "%(hbg_)s" 
            bg[ACTIVE] = "%(bg_)s" 
            bg[INSENSITIVE] = "%(hbg_)s"
            base[NORMAL] = "%(hbg_)s"
            base[ACTIVE] = "%(bg_)s" 
            base[PRELIGHT] = "%(bg_)s"
            base[INSENSITIVE] = "%(hbg_)s"
            base[SELECTED]     = "%(bg_)s"

            }

            style "menuitem"    #one of menu items    
            {
            bg[NORMAL] = "%(hbg_)s" 
            bg[ACTIVE] = "%(bg_)s" 
            bg[PRELIGHT] = "%(bg_)s" 
            bg[SELECTED] = "%(bg_)s" 
            bg[INSENSITIVE] = "%(hbg_)s"

            fg[NORMAL] = "%(hfg_)s" 
            fg[ACTIVE] = "%(fg_)s" 
            fg[PRELIGHT] = "%(fg_)s" 
            fg[SELECTED] = "%(fg_)s" 
            fg[INSENSITIVE] = "%(fg_)s" 
            }

            class "GtkMenu"             style "menuitem"
            widget_class "*.<MenuItem>."    style "menuitem"
            class "GtkMenuItem"        style "menuitem"
            class "GtkTearoffMenuItem"    style "menuitem"
            #widget_class "*GtkToolbar*" style "toolbar-color"
            """ % {
                'fg_':self.fg, 
                'bg_':self.bg, 
                'hfg_':self.hfg, 
                'hbg_':self.hbg}
        self.__make_dirs(self.__output_dir+'/gtk-2.0/colorrc')
        f = open(self.__output_dir+'/gtk-2.0/colorrc', 'w')
        f.write(strings)
        f.close()

    def _copy(self, input):
        dir = os.path.dirname(self.__output_dir+'/gtk-2.0/'+input)
        if not os.path.exists(dir):
            os.makedirs(dir)
        f = open(self.__resource_dir+'/gtk-2.0/'+input, 'r')
        a = f.read()
        f.close()
        f = open(self.__output_dir+'/gtk-2.0/'+input, 'w')
        f.write(a)
        f.close()

